
name: Cypress Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_baseUrl: ${{ secrets.CYPRESS_BASE_URL }}

      - name: Merge Mochawesome JSON reports
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json

      - name: Generate HTML report
        run: npx marge cypress/reports/report.json -o cypress/reports/html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/reports/html